title: LinLyra's Universe
email: your@email.com   # 你想放的联系邮箱，也可以留空
description: >-
  Welcome to my Universe! Explore my projects, competitions, learning journey and more.

twitter_username: ""
github_username: LinLyra
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Australia/Sydney

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "LinLyra"
  avatar : "/assets/images/bio-photo.jpg"  # 先留着默认，你以后可以换成小人或者卡通头像
  bio    : "Lifelong Learner. Curiosity-driven. Data Science & Business Analytics @ University of Sydney."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LinLyra"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your@email.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LinLyra"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
